spring.application.name=Blog-API

#DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/blogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Meraj@26092001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# UPLOADED FILES
file.upload-dir=uploads/

# MAIL CONFIGURATION
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=7e4d1f0daac38d
spring.mail.password=45df28d7fc7825
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html